name: Build app
on:
  push:
    branches:
      - master
    paths:
      - app/**
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          cd app
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: app/dist
          CLEAN: false
          GIT_CONFIG_NAME: build-app-bot
          GIT_CONFIG_EMAIL: build-app@bot.bot

